# Operations list 1

1. a + b : np.add(a, b)
2. a - b : np.subtract(a, b)
3. a * b : np.multiply(a, b)
4. a / b : np.divide(a, b)
5. a % b : np.mod(a, b)
6. a ** b : np.power(a, b)
7. 1 / a : np.reciprocal(a)

In [2]:
import numpy as np

## 1D Operations

In [15]:
# Normal operations

arr = [1, 2, 3, 4, 5]
change = 3 # also try [1, 2, 3, 4, 5]
arr1 = np.array(arr)

print(f"Addition: {arr1 + change}")
print(f"Subtraction: {arr1 - change}")
print(f"Multiplication: {arr1 * change}")
print(f"Division: {arr1 / change}")
print(f"Mode: {arr1 % change}")
print(f"Power: {arr1 ** change}")
print(f"Reciprocal: {1 // arr1}")

Addition: [4 5 6 7 8]
Subtraction: [-2 -1  0  1  2]
Multiplication: [ 3  6  9 12 15]
Division: [0.33333333 0.66666667 1.         1.33333333 1.66666667]
Mode: [1 2 0 1 2]
Power: [  1   8  27  64 125]
Reciprocal: [1 0 0 0 0]


In [16]:
# Functional operations

arr = [1, 2, 3, 4, 5]
change = 3 # also try [1, 2, 3, 4, 5]
arr1 = np.array(arr)

print(f"Addition: {np.add(arr1, change)}")
print(f"Subtraction: {np.subtract(arr1, change)}")
print(f"Multiplication: {np.multiply(arr1, change)}")
print(f"Division: {np.divide(arr1, change)}")
print(f"Mode: {np.mod(arr1, change)}")
print(f"Power: {np.power(arr1, change)}")
print(f"Reciprocal: {np.reciprocal(arr1)}")

Addition: [4 5 6 7 8]
Subtraction: [-2 -1  0  1  2]
Multiplication: [ 3  6  9 12 15]
Division: [0.33333333 0.66666667 1.         1.33333333 1.66666667]
Mode: [1 2 0 1 2]
Power: [  1   8  27  64 125]
Reciprocal: [1 0 0 0 0]


## 2D Operations


In [17]:
# Normal operations

arr = [[1, 2, 3], [4, 5, 6]]
change = 3 # also try [[9, 8, 7], [6, 5, 4]]
arr1 = np.array(arr)

print(f"Addition: \n{arr1 + change}")
print(f"Subtraction: \n{arr1 - change}")
print(f"Multiplication: \n{arr1 * change}")
print(f"Division: \n{arr1 / change}")
print(f"Mode: \n{arr1 % change}")
print(f"Power: \n{arr1 ** change}")
print(f"Reciprocal: \n{1 // arr1}")

Addition: 
[[4 5 6]
 [7 8 9]]
Subtraction: 
[[-2 -1  0]
 [ 1  2  3]]
Multiplication: 
[[ 3  6  9]
 [12 15 18]]
Division: 
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]]
Mode: 
[[1 2 0]
 [1 2 0]]
Power: 
[[  1   8  27]
 [ 64 125 216]]
Reciprocal: 
[[1 0 0]
 [0 0 0]]


In [18]:
# Functional operations

arr = [[1, 2, 3], [4, 5, 6]]
change = 3 # also try [[9, 8, 7], [6, 5, 4]]
arr1 = np.array(arr)

print(f"Addition: \n{np.add(arr1, change)}")
print(f"Subtraction: \n{np.subtract(arr1, change)}")
print(f"Multiplication: \n{np.multiply(arr1, change)}")
print(f"Division: \n{np.divide(arr1, change)}")
print(f"Mode: \n{np.mod(arr1, change)}")
print(f"Power: \n{np.power(arr1, change)}")
print(f"Reciprocal: \n{np.reciprocal(arr1)}")

Addition: 
[[4 5 6]
 [7 8 9]]
Subtraction: 
[[-2 -1  0]
 [ 1  2  3]]
Multiplication: 
[[ 3  6  9]
 [12 15 18]]
Division: 
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]]
Mode: 
[[1 2 0]
 [1 2 0]]
Power: 
[[  1   8  27]
 [ 64 125 216]]
Reciprocal: 
[[1 0 0]
 [0 0 0]]


# Operations list 2

1. np.min(x)
2. np.max(x)
3. np.argmin(x)
4. np.argmax(x)
5. np.sqrt(x)
6. np.sin(x)
7. np.cos(x)
8. np.tan(x)
9. np.cumsum(x) // Prefix sum

## 1D Operations

In [39]:
# Functional operations

arr = [9, 64, 81, 16]
arr1 = np.array(arr)

print(f"Min: {np.min(arr1)}")
print(f"Max: {np.max(arr1)}")
print(f"Arg Min Index: {np.argmin(arr1)}")
print(f"Arg Max Index: {np.argmax(arr1)}")
print(f"Sqrt: {np.sqrt(arr1)}")
print(f"Sin: {np.sin(arr1)}")
print(f"Cos: {np.cos(arr1)}")
print(f"Tan: {np.tan(arr1)}")
print(f"Cumsum: {np.cumsum(arr1)}")

Min: 9
Max: 81
Arg Min Index: 0
Arg Max Index: 2
Sqrt: [3. 8. 9. 4.]
Sin: [ 0.41211849  0.92002604 -0.62988799 -0.28790332]
Cos: [-0.91113026  0.39185723  0.77668598 -0.95765948]
Tan: [-0.45231566  2.34786031 -0.81099442  0.30063224]
Cumsum: [  9  73 154 170]


## 2D Operations

In [40]:
# Functional operations

# (Optional) only in 2D
# Axis 0 = Col
# Axis 1 = Row

arr = [[9,  64, 36,  4], 
       [25, 1,  81, 16]]
arr1 = np.array(arr)

print(f"Min Axis 0: {np.min(arr1, axis = 0)}")
print(f"Min Axis 1: {np.min(arr1, axis = 1)}")
print(f"Max Axis 0: {np.max(arr1, axis = 0)}")
print(f"Max Axis 1: {np.max(arr1, axis = 1)}")
print(f"Arg Min Index Axis 0: {np.argmin(arr1, axis = 0)}")
print(f"Arg Min Index Axis 1: {np.argmin(arr1, axis = 1)}")
print(f"Arg Max Index Axis 0: {np.argmax(arr1, axis = 0)}")
print(f"Arg Max Index Axis 1: {np.argmax(arr1, axis = 1)}")
print(f"Sqrt: \n{np.sqrt(arr1)}")
print(f"Sin: \n{np.sin(arr1)}")
print(f"Cos: \n{np.cos(arr1)}")
print(f"Tan: \n{np.tan(arr1)}")
print(f"Cumsum: \n{np.cumsum(arr1)}")

Min Axis 0: [ 9  1 36  4]
Min Axis 1: [4 1]
Max Axis 0: [25 64 81 16]
Max Axis 1: [64 81]
Arg Min Index Axis 0: [0 1 0 0]
Arg Min Index Axis 1: [3 1]
Arg Max Index Axis 0: [1 0 1 1]
Arg Max Index Axis 1: [1 2]
Sqrt: 
[[3. 8. 6. 2.]
 [5. 1. 9. 4.]]
Sin: 
[[ 0.41211849  0.92002604 -0.99177885 -0.7568025 ]
 [-0.13235175  0.84147098 -0.62988799 -0.28790332]]
Cos: 
[[-0.91113026  0.39185723 -0.12796369 -0.65364362]
 [ 0.99120281  0.54030231  0.77668598 -0.95765948]]
Tan: 
[[-0.45231566  2.34786031  7.75047091  1.15782128]
 [-0.13352641  1.55740772 -0.81099442  0.30063224]]
Cumsum: 
[  9  73 109 113 138 139 220 236]
