## Brodcast error

    It occurs when 2 array / matrix are not same while performing some operations

### Solutions

1. Shape / Dimensions should be same
2. if not same:
    compare from the right and shoud have 1 shape any one of them
    example:
    
        x1  y1  x2  y2
    1. (1 x 3) (1 x 4) = error
    2. (1 x 3) (5 x 1) = works
    3. (1 x 3) (3 x 3) = works
    
    y1 & y2 should be same OR any one of them should be 1

In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4]
data2 = [1, 2, 3]

arr1 = np.array(data1)
arr2 = np.array(data2)

print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
data1 = [1, 2, 3]
data2 = [[1], [2], [3]]

arr1 = np.array(data1)
arr2 = np.array(data2)

print(f"Shape of {arr1}: {arr1.shape}")
print(f"Shape of \n{arr2} : {arr2.shape}")

print(f"Addition : \n{arr1 + arr2}")

Shape of [1 2 3]: (3,)
Shape of 
[[1]
 [2]
 [3]] : (3, 1)
Addition : 
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [12]:
# example2: (1 x 3) (5 x 1)

data1 = [1, 2, 3]
data2 = [[1], [2], [3], [4], [5]]

arr1 = np.array(data1)
arr2 = np.array(data2)

print(f"Shape of {arr1}: {arr1.shape}")
print(f"Shape of \n{arr2} : {arr2.shape}")

print(f"Addition : \n{arr1 + arr2}")

Shape of [1 2 3]: (3,)
Shape of 
[[1]
 [2]
 [3]
 [4]
 [5]] : (5, 1)
Addition : 
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


In [13]:
# example3: (1 x 3) (3 x 3)

data1 = [1, 2, 3]
data2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr1 = np.array(data1)
arr2 = np.array(data2)

print(f"Shape of {arr1}: {arr1.shape}")
print(f"Shape of \n{arr2} : {arr2.shape}")

print(f"Addition : \n{arr1 + arr2}")

Shape of [1 2 3]: (3,)
Shape of 
[[1 2 3]
 [4 5 6]
 [7 8 9]] : (3, 3)
Addition : 
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
