In [2]:
import numpy as np

## concatenate()

In [24]:
# 1D example

data1 = [1, 2, 3]
data2 = [4, 5, 6]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.concatenate((arr1, arr2))
print(f"1D concatenate: {arr}")

1D concatenate: [1 2 3 4 5 6]


In [10]:
# 2D example | axis = 0 (default)

data1 = [[1, 2], [3, 4]]
data2 = [[4, 5], [6, 7]]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.concatenate((arr1, arr2))
print(f"2D concatenate: \n{arr}")

2D concatenate: 
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [11]:
# 2D example | axis = 1

data1 = [[1, 2], [3, 4]]
data2 = [[4, 5], [6, 7]]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.concatenate((arr1, arr2), axis = 1)
print(f"2D concatenate: \n{arr}")

2D concatenate: 
[[1 2 4 5]
 [3 4 6 7]]


## stack() 1D

In [15]:
# 1D example | axis = 0 (default)

data1 = [1, 2, 3]
data2 = [4, 5, 6]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.stack((arr1, arr2))
print(f"1D concatenate: \n{arr}")

1D concatenate: 
[[1 2 3]
 [4 5 6]]


In [16]:
# 1D example | axis = 1

data1 = [1, 2, 3]
data2 = [4, 5, 6]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.stack((arr1, arr2), axis = 1)
print(f"1D concatenate: \n{arr}")

1D concatenate: 
[[1 4]
 [2 5]
 [3 6]]


In [25]:
# 1D example

data1 = [1, 2, 3]
data2 = [4, 5, 6]

arr1 = np.array(data1)
arr2 = np.array(data2)

arrV = np.vstack((arr1, arr2)) # Cols - vertical - stack - axis = 0
arrH = np.hstack((arr1, arr2)) # Rows - horizontal - concatenate - axis = 1
arrD = np.dstack((arr1, arr2)) # heights - depth

print(f"2D vstack: \n{arrV}")
print(f"1D hstack: \n{arrH}")
print(f"1D dstack: \n{arrD}")

2D vstack: 
[[1 2 3]
 [4 5 6]]
1D hstack: 
[1 2 3 4 5 6]
1D dstack: 
[[[1 4]
  [2 5]
  [3 6]]]


## stack() 2D

In [26]:
# 2D example | axis = 0 (default)

data1 = [[1, 2], [3, 4]]
data2 = [[4, 5], [6, 7]]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.stack((arr1, arr2))
print(f"2D concatenate: \n{arr}")

2D concatenate: 
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [27]:
# 2D example | axis = 1

data1 = [[1, 2], [3, 4]]
data2 = [[4, 5], [6, 7]]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr = np.stack((arr1, arr2), axis = 1)
print(f"2D concatenate: \n{arr}")

2D concatenate: 
[[[1 2]
  [4 5]]

 [[3 4]
  [6 7]]]


In [28]:
# 2D example

data1 = [[1, 2], [3, 4]]
data2 = [[4, 5], [6, 7]]

arr1 = np.array(data1)
arr2 = np.array(data2)

arrV = np.vstack((arr1, arr2)) # Cols - vertical - concatenate - axis = 0
arrH = np.hstack((arr1, arr2)) # Rows - horizontal - concatenate - axis = 1
arrD = np.dstack((arr1, arr2)) # heights - depth

print(f"2D vstack: \n{arrV}")
print(f"2D hstack: \n{arrH}")
print(f"2D dstack: \n{arrD}")

2D vstack: 
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
2D hstack: 
[[1 2 4 5]
 [3 4 6 7]]
2D dstack: 
[[[1 4]
  [2 5]]

 [[3 6]
  [4 7]]]


## split() 1D

In [42]:
# 1D example | axis = 0 (default)

data = [1, 2, 3, 4, 5, 6]

arr = np.array(data)
arrs = np.array_split(arr, 3)

print(f"1D array_split: \n{arrs}")
for ar in arrs:
    print(ar)

1D array_split: 
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


## split 2D

In [43]:
# 2D example | axis = 0 (default)

data = [[1, 2], [3, 4]]

arr = np.array(data)
arrs = np.array_split(arr, 2)

print(f"2D array_split: \n{arrs}")
for ar in arrs:
    print(ar)

2D array_split: 
[array([[1, 2]]), array([[3, 4]])]
[[1 2]]
[[3 4]]


In [44]:
# 2D example | axis = 1

data = [[1, 2], [3, 4]]

arr = np.array(data)
arrs = np.array_split(arr, 2, axis = 1)

print(f"2D array_split: \n{arrs}")
for ar in arrs:
    print(ar)

2D array_split: 
[array([[1],
       [3]]), array([[2],
       [4]])]
[[1]
 [3]]
[[2]
 [4]]
