# Data types

1. bool_ : Booleans (True, False)
2. int_ : Default int type (same as C long; int64 or int32)
3. intc : C int (int 32 or int64)
4. intp : integer used for indexing (C ssize_t: 32 or 64)
5. int8 : Byte (-128 to 127)
6. int16 : Integer (-32768 to 32767)
7. int32 : integer (-2147... to 2147...)
8. int64 : integer (-92233... to 92233...)
9. uint8 : Unsigned integer (0 to 255)
10. uint16 : Unsigned integer (0 to 65535)
11. uint32 : Unsigned integer (0 to 42949...)
12. uint64 : Unsigned integer (0 to 18446...)
13. float_ : Shorthand for float64
14. float16 : Half pricision float: sign bit, 5 bits exponent, 10 bits mantissa
15. float32 : Single pricision float: sign bit, 8 bits exponent, 10 bits mantissa
16. float64 : Double pricision float: sign bit, 11 bits exponent, 10 bits mantissa
17. complex_ : Shorthand for complex128 
18. complex64 : 32 bit float (real and imaginary components)
19. complex128 : 64 bit float (real and imaginary components)

In [1]:
import numpy as np

In [6]:
dataTypes = [
    [1, 2, 3],
    [1.1, 2.2],
    ['a', 'b'],
    ["abc", "def"],
    [1, 1.5],
#     [1, 'a']
    [1, "abc"],
    [1.1, 'a'],
    [1.1, "abc"],
    ['a', "abc"]
]

for data in dataTypes:
    arr = np.array(data)
    print(f"{data} \t: \t{arr.dtype}")

[1, 2, 3] 	: 	int64
[1.1, 2.2] 	: 	float64
['a', 'b'] 	: 	<U1
['abc', 'def'] 	: 	<U3
[1, 1.5] 	: 	float64
[1, 'abc'] 	: 	<U21
[1.1, 'a'] 	: 	<U32
[1.1, 'abc'] 	: 	<U32
['a', 'abc'] 	: 	<U3


# Data type alias

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other types (void)

In [14]:
# np.dataType is function so can use individually

dataTypesShorAndLong = [
    np.int8,
    np.int16,
    np.int32,
    np.int64,
    np.uint8,
    np.uint16,
    np.uint32,
    np.uint64, 
    np.float32,    
    np.float64,
    "i",
    "f",
    "S",
    "O"   
]

for dataType in dataTypesShorAndLong:
    arr = np.array([1, 2, 3], dtype = dataType)
    print(f"{arr} : {arr.dtype}")

[1 2 3] : int8
[1 2 3] : int16
[1 2 3] : int32
[1 2 3] : int64
[1 2 3] : uint8
[1 2 3] : uint16
[1 2 3] : uint32
[1 2 3] : uint64
[1. 2. 3.] : float32
[1. 2. 3.] : float64
[1 2 3] : int32
[1. 2. 3.] : float32
[b'1' b'2' b'3'] : |S1
[1 2 3] : object


In [16]:
arrConvert = np.array([1, 2, 3])
arrConvert = np.float32(arrConvert)

print(f"{arrConvert} : {arrConvert.dtype}")

[1. 2. 3.] : float32


In [ ]:
arrConvert = np.float32(arrConvert)

print(f"{arrConvert} : {arrConvert.dtype}")