In [4]:
import numpy as np

# Indexing

## Indexing 1D

    array:   [1,  2,  3,  4]
    index:    0,  1,  2,  3
    rev-ind: -4, -3, -2, -1
    
    Shape: (1 x 4)

In [6]:
data = [1, 2, 3, 4]
arr = np.array(data)

print(f"index  1: {arr[1]}")
print(f"index -1: {arr[-1]}")

index  1: 2
index -1: 4


## Indexing 2D
      
      Rows
      0 [[1, 2, 3],
      1  [4, 5, 6]]
          0  1  2   Cols
          
      Shape: (2 x 3)      

In [16]:
data = [[1, 2, 3],[4, 5, 6]]
arr = np.array(data)

print(f"index [1][1]: {arr[1][1]}")
print(f"index [1, 1]: {arr[1, 1]}")

index [1][1]: 5
index [1, 1]: 5


## Indexing 3D



In [15]:
data = [[[1, 2], [8, 7]]]
arr = np.array(data)

print(f"index [0][0][1]: {arr[0][0][1]}")
print(f"index [0, 0, 1]: {arr[0, 0, 1]}")
print(f"3D Array : \n{arr}")

index [0][0][1]: 2
index [0, 0, 1]: 2
3D Array : 
[[[1 2]
  [8 7]]]


# Slicing (same as string)

    [start : stop : step]

## Slicing 1D

    array:   [1,  2,  3,  4]
    index:    0,  1,  2,  3
    rev-ind: -4, -3, -2, -1

In [36]:
data = [1, 2, 3, 4, 5, 6, 7, 8 ,9]
arr = np.array(data)

print(f"1D Array: {arr}")
print(f"index [2 : 5]        : {arr[2:5]}")
print(f"index [2 : end]      : {arr[2:]}")
print(f"index [-7::]         : {arr[-7::]}")
print(f"index [start : 5]    : {arr[:5]}")
print(f"index [-9 : 5]       : {arr[-9:5]}")
print(f"index [:: -1]        : {arr[::-1]}")
print(f"index [6:2:-1]       : {arr[6:2:-1]}")
print(f"index [1:7:2]        : {arr[1:7:2]}")
print(f"index [7:1:-2]       : {arr[7:1:-2]}")

1D Array: [1 2 3 4 5 6 7 8 9]
index [2 : 5]        : [3 4 5]
index [2 : end]      : [3 4 5 6 7 8 9]
index [-7::]         : [3 4 5 6 7 8 9]
index [start : 5]    : [1 2 3 4 5]
index [-9 : 5]       : [1 2 3 4 5]
index [:: -1]        : [9 8 7 6 5 4 3 2 1]
index [6:2:-1]       : [7 6 5 4]
index [1:7:2]        : [2 4 6]
index [7:1:-2]       : [8 6 4]


## Slicing 2D

    Rows
    0 [[1, 2, 3],
    1  [4, 5, 6]]
        0  1  2   Cols

In [43]:
data = [[1, 2, 3, 4, 5], [6, 7, 8 ,9, 10]]
arr = np.array(data)

print(f"2D Array: \n{arr}")
print(f"index [1][1 : 4]        : {arr[1, 1:4]}")
print(f"index [0][2 : end]      : {arr[0, 2:]}")

2D Array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
index [1][1 : 4]        : [7 8 9]
index [0][2 : end]      : [3 4 5]


## Slicing 3D

In [44]:
# just add commas(,)

# emaple:
# arr[0, 0, ]