In [1]:
import numpy as np

# Insert(array, pos, val, axis)

In [8]:
# 1D

data = [1, 2, 3]

arr = np.array(data)
print(f"Original: {arr}")

pos = 1
val = 100
ans = np.insert(arr, pos, val)
print(f"{val} inserted at {pos}: {ans}")

pos = (0, 2)
val = 10
ans = np.insert(arr, pos, val)
print(f"{val} inserted at {pos}: {ans}")

Original: [1 2 3]
100 inserted at 1: [  1 100   2   3]
10 inserted at (0, 2): [10  1  2 10  3]


In [16]:
# 2D

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr = np.array(data)
print(f"Original: \n{arr}")

pos = 2
val = 100
ans = np.insert(arr, pos, val, axis = 0)
print(f"{val} inserted at {pos}: \n{ans}")

pos = 1
val = 100
ans = np.insert(arr, pos, val, axis = 1)
print(f"{val} inserted at {pos}: \n{ans}")

pos = 2
val = [100, 200, 300]
ans = np.insert(arr, pos, val, axis = 0)
print(f"{val} inserted at {pos}: \n{ans}")

pos = 1
val = [100, 200, 300]
ans = np.insert(arr, pos, val, axis = 1)
print(f"{val} inserted at {pos}: \n{ans}")

Original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
100 inserted at 2: 
[[  1   2   3]
 [  4   5   6]
 [100 100 100]
 [  7   8   9]]
100 inserted at 1: 
[[  1 100   2   3]
 [  4 100   5   6]
 [  7 100   8   9]]
[100, 200, 300] inserted at 2: 
[[  1   2   3]
 [  4   5   6]
 [100 200 300]
 [  7   8   9]]
[100, 200, 300] inserted at 1: 
[[  1 100   2   3]
 [  4 200   5   6]
 [  7 300   8   9]]


# Append(array, value, axis)
    
    Append val at the end of array

In [22]:
# 1D

data = [1, 2, 3]

arr = np.array(data)
print(f"Original: {arr}")

val = 100
ans = np.append(arr, val)
print(f"{val} appended at the end: {ans}")

val = [10, 20]
ans = np.append(arr, val)
print(f"{val} appended at the end: {ans}")

Original: [1 2 3]
100 appended at the end: [  1   2   3 100]
[10, 20] appended at the end: [ 1  2  3 10 20]


In [35]:
# 2D

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr = np.array(data)
print(f"Original: {arr}")

val = [[100, 200, 300]]
ans = np.append(arr, val, axis = 0)
print(f"{val} appended at the end row: \n{ans}")

val = [[10], [20], [30]]
ans = np.append(arr, val, axis = 1)
print(f"{val} appended at the end col: \n{ans}")

Original: [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100, 200, 300]] appended at the end row: 
[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [100 200 300]]
[[10], [20], [30]] appended at the end col: 
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


# Delete(array, index, axis)

In [40]:
# 1D

data = [10, 20, 30, 40, 50]

arr = np.array(data)
print(f"Original: {arr}")

ind = 1
ans = np.delete(arr, ind)
print(f"{arr[ind]} value Deleted: {ans}")

ind = [1, 2]
ans = np.delete(arr, ind)
print(f"{arr[ind]} value Deleted: {ans}")

Original: [10 20 30 40 50]
20 value Deleted: [10 30 40 50]
[20 30] value Deleted: [10 40 50]


In [46]:
# 2D

data = [[10, 20], [30, 40], [50, 60]]

arr = np.array(data)
print(f"Original: \n{arr}")

ind = 1
ans = np.delete(arr, ind, axis = 0)
print(f"{arr[ind]} value Deleted: \n{ans}")

ind = 1
ans = np.delete(arr, ind, axis = 1)
print(f"{arr[]} value Deleted: \n{ans}")

Original: 
[[10 20]
 [30 40]
 [50 60]]
[30 40] value Deleted: 
[[10 20]
 [50 60]]
[30 40] value Deleted: 
[[10]
 [30]
 [50]]
