In [1]:
import numpy as np

# Matrix

    1. Matrix vs Array
    2. operations like +, -, / works same
    3. * = dot() works with matrix

In [5]:
# matrix VS Array

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

mat = np.matrix(data)
arr = np.array(data)

print(f"{type(mat)}\n{mat}")
print(f"{type(arr)}\n{arr}")

<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# +, -, / , *, dot()

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

mat1 = np.matrix(data)
mat2 = np.matrix(data)

print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 / mat2)
print(mat1 * mat2)
print(mat1.dot(mat2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Functions

    1. Transpose
    2. Swapaxes
    3. Inverse
    4. power
    5. Determinate

In [13]:
# Transpose

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

mat = np.matrix(data)
print(f"Original: \n{mat}")

ans = np.transpose(mat)
print(f"Transpose: \n{ans}")

ans = mat.T
print(f"Transpose: \n{ans}")

Original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
# Swap axes

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

mat = np.matrix(data)
print(f"Original: \n{mat}")

ans = np.swapaxes(mat, 0, 1)
print(f"Swap axex: \n{ans}")

Original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Swap axex: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
# inverse

data = [[1, 2], [3, 4]]

mat = np.matrix(data)
print(f"Original: \n{mat}")

ans = np.linalg.inv(mat)
print(f"Inverse: \n{ans}")

Original: 
[[1 2]
 [3 4]]
Inverse: 
[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
# power

data = [[1, 2], [3, 4]]

mat = np.matrix(data)
print(f"Original: \n{mat}")

power = 2
ans = np.power(mat, power)
print(f"Power: \n{ans}")

power = 2
ans = np.linalg.matrix_power(mat, power)
print(f"Power: \n{ans}")

power = 0
ans = np.linalg.matrix_power(mat, power)
print(f"Power: \n{ans}")

power = -2
ans = np.linalg.matrix_power(mat, power)
print(f"Power: \n{ans}")

Original: 
[[1 2]
 [3 4]]
Power: 
[[ 1  4]
 [ 9 16]]
Power: 
[[ 7 10]
 [15 22]]
Power: 
[[1 0]
 [0 1]]
Power: 
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [34]:
# Determinate

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# data = [[1, 2], [3, 4]]

mat = np.matrix(data)
print(f"Original: \n{mat}")

ans = np.linalg.det(mat)
print(f"Determinate: \n{ans}")

Original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinate: 
-9.51619735392994e-16
