In [1]:
import numpy as np

In [4]:
 # Difference between list and array
    
lst = [1, 2, 3, 4]
arr = np.array(lst)

print(f"List: {lst}, data type {type(lst)}")  # Comma separated
print(f"Array: {arr}, data type {type(arr)}") # No commas

List: [1, 2, 3, 4], data type <class 'list'>
Array: [1 2 3 4], data type <class 'numpy.ndarray'>


# Basic difference List vs Array

### 1. Data types storage
    1. List ['a', "abc", a, a.5, True]
    2. Array Only 1 type of data [1, 2], ['a', 'b']
    
### 2. Import module
    1. inbuilt so, not needed
    2. import numpy as np
    
### 3. Numerical operation
    1. Capable but less efficiency
    2. Fast, capable, more efficient, can convert to matrix
    
### 4. Modification capabilities
    1. Fast, more functions available
    2. Slow comparing list, not much functions available
    
### 5. Memory
    1. More
    2. Less
    
### 6. Speed
    1. Slow
    2. Fast
    
### 7. Convenient to use
    1. Not as numpay array
    2. Fast & easy
    

# Check time of executions for both

1. for 1 line -%time
2. for full progrm - %%timeit

In [13]:
# Time comparision

print("List: ")
%timeit [i ** 4 for i in range(1, 9)]

print("Array: ")
%timeit np.arange(1, 9) ** 4

List: 
341 ns ± 2.09 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
Array: 
820 ns ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Create n dimension Array in Numpy

In [23]:
dimensions = int(input("Enter dimentions: "))

arrDimension = np.array([1,2,3], ndmin = dimensions)
print(f"Dimensions: {arrDimension.ndim}")
print(f"Array with {dimensions} dimensions: {arrDimension}")

# create manually

print(np.array([1,2,3])) # 1D
print(np.array([[1,2,3]])) # 2D
print(np.array([[[1,2,3]]])) # 3D

Enter dimentions: 3
Dimensions: 3
Array with 3 dimensions: [[[1 2 3]]]
[1 2 3]
[[1 2 3]]
[[[1 2 3]]]


# Special Numpy Array's

In [32]:
# Array filld with 0's

arr_zeros_1d = np.zeros(4)
arr_zeros_2d = np.zeros((2,3))

print(arr_zeros_1d)
print(arr_zeros_2d)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# Array filld with 1's

arr_ones_1d = np.ones(4)
arr_ones_2d = np.ones((2,3))

print(arr_ones_1d)
print(arr_ones_2d)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
# Empty array
# Default values are previous memory value
# execute 1's block then empty will give 1 values
# execute 0's block then empty will give 0 values

arr_empty_1d = np.empty(4)
arr_empty_2d = np.empty((2,3))

print(arr_empty_1d)
print(arr_empty_2d)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
# Range array

arr_arange_1d = np.arange(4)

print(arr_arange_1d)

[0 1 2 3]


In [40]:
# Diagonal array filld with 1's

arr_diagonal_n_by_n = np.eye(4)
arr_diagonal_m_by_n = np.eye(2,3)

print(arr_diagonal_n_by_n)
print(arr_diagonal_m_by_n)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]


In [47]:
# Array filld with values that are spaced linearly in a specified interval gap

arr_linspace_1d = np.linspace(0, 12, num = 7)

print(arr_linspace_1d)

[ 0.  2.  4.  6.  8. 10. 12.]


# Create Numpy Array's with Random Numbers

In [57]:
# rand() - generates number between 0 to 1 (positive only)

arr_rand_1d = np.random.rand(4)
arr_rand_2d = np.random.rand(2, 3)

print(arr_rand_1d)
print(arr_rand_2d)

[0.66440186 0.33168875 0.3919262  0.93763625]
[[0.8415692  0.65411072 0.85592915]
 [0.96593481 0.97611719 0.29254862]]


In [60]:
# randn() - generates number close to 0 (positive & negative)

arr_randn_1d = np.random.randn(4)
arr_randn_2d = np.random.randn(2, 3)

print(arr_randn_1d)
print(arr_randn_2d)

[ 0.3981524  -0.22502283  0.75984889  1.24998108]
[[-0.03640987 -0.78210224 -1.10752287]
 [-0.3195955  -1.16142857 -0.54389915]]


In [62]:
# ranf() - generates number between 0.0 to 1.0 (positive & 1.0 not included)

arr_ranf_1d = np.random.ranf(4)

print(arr_ranf_1d)

[0.86543427 0.58435556 0.11256264 0.87380781]


In [66]:
# randint() - generates number in between min to max

arr_randint_1d = np.random.randint(1, 100, 4) # min, max, total_values

print(arr_randint_1d)

[15 73 84 75]
