# Shape
    
    This gives he size of array
    Example: [[1,2,3],[4,5,6]]
    Shape: (2, 3)

In [1]:
import numpy as np

In [4]:
data = [[1, 2, 3], [4, 5, 6]]
arr = np.array(data)

print(arr.shape)

(2, 3)


In [5]:
data = [1, 2, 3]
arr = np.array(data, ndmin = 5)

print(arr.shape)

(1, 1, 1, 1, 3)


# Reshape

In [9]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(data)

print(arr.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
