In [1]:
import numpy as np

# Search index in any Array

In [15]:
data = [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]

arr = np.array(data)

ans = np.where(arr == 4)
print(f"Indexes of 4's: {ans}")

ans = np.where(arr % 2 == 0)
print(f"Indexes of even vals: {ans}")
ans = np.where(arr % 2 != 0)
print(f"Indexes of odd vals: {ans}")
ans = np.where(arr & 1)
print(f"Indexes of odd vals: {ans}")

Indexes of 4's: (array([ 3,  7, 12]),)
Indexes of even vals: (array([ 0,  3,  4,  5,  6,  7,  8, 10, 12, 14]),)
Indexes of odd vals: (array([ 1,  2,  9, 11, 13]),)
Indexes of odd vals: (array([ 1,  2,  9, 11, 13]),)


# Search adding val index in Sorted Array

In [29]:
# Left to Right (default)

data = [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]
data.sort()

arr = np.array(data)
insert = 110

ans = np.searchsorted(arr, insert)
print(f"{insert} can be placed at: {ans} index")

110 can be placed at: 13 index


In [30]:
# Right to Left
data = [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]
data.sort()

arr = np.array(data)
insert = 110

ans = np.searchsorted(arr, insert, side="right")
print(f"{insert} can be placed at: {ans} index")

110 can be placed at: 13 index


In [31]:
# find index of array

data = [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]
data.sort()

arr = np.array(data)
insert = [5, 9, 44]

ans = np.searchsorted(arr, insert)
print(f"{insert} can be placed at: {ans} index")

[5, 9, 44] can be placed at: [6 7 9] index


# Sort Array

In [42]:
#  1D

data = [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]

arr = np.array(data)

ans = np.sort(arr)
print(f"Sorted: {ans}")

Sorted: [  2   2   2   4   4   4   5  32  43  53  54  56  57 676 745]


In [43]:
#  2D

data = [[2, 43, 5], [4, 2, 2], [54, 4, 56], [57, 676, 745], [4, 53, 32]]

arr = np.array(data)

ans = np.sort(arr)
print(f"Sorted: \n{ans}")

Sorted: 
[[  2   5  43]
 [  2   2   4]
 [  4  54  56]
 [ 57 676 745]
 [  4  32  53]]


# Filter() Array

In [45]:
#  1D

data = ["jan", "feb", "march", "apr", "may", "jun", "july", "aug", "sept", "oct", "nov", "dec"]
fitr = [True, False, False, False, True, False, True, False, False, True, False, True]

arr = np.array(data)

ans = arr[fitr]
print(f"Filtered: {ans}")

Filtered: ['jan' 'may' 'july' 'oct' 'dec']


# Shuffle
    
    shuffle the data

In [48]:
data = ["jan", "feb", "march", "apr", "may", "jun", "july", "aug", "sept", "oct", "nov", "dec"]

arr = np.array(data)

np.random.shuffle(arr)
print(f"Shuffled: {arr}")

Shuffled: ['nov' 'dec' 'feb' 'may' 'oct' 'jan' 'sept' 'apr' 'jun' 'july' 'march'
 'aug']


# Unique

In [54]:
data =  [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]

arr = np.array(data)

ans = np.unique(arr, return_index=True, return_inverse=True, return_counts=True)
print(f"Unique  : {ans[0]}")
print(f"Indexes : {ans[1]}")
print(f"Inverse : {ans[2]}")
print(f"Counts  : {ans[3]}")
print(f"Original: {arr}")

Unique  : [  2   4   5  32  43  53  54  56  57 676 745]
Indexes : [ 0  3  2 14  1 13  6  8  9 10 11]
Inverse : [ 0  4  2  1  0  0  6  1  7  8  9 10  1  5  3]
Counts  : [3 3 1 1 1 1 1 1 1 1 1]
Original: [  2  43   5   4   2   2  54   4  56  57 676 745   4  53  32]


# Resize

In [62]:
data =  [2, 43, 5, 4, 2, 2, 54, 4, 56, 57, 676, 745, 4, 53, 32]

arr = np.array(data)

ans = np.resize(arr, (3, 3))
print(f"Original: {arr}")
print(f"Resize: \n{ans}")

Original: [  2  43   5   4   2   2  54   4  56  57 676 745   4  53  32]
Resize: 
[[ 2 43  5]
 [ 4  2  2]
 [54  4 56]]


# Flatten()

In [74]:
data = [[2, 43, 5], [4, 2, 2], [54, 4, 56], [57, 676, 745], [4, 53, 32]]

arr = np.array(data)
print(f"Original: \n{arr}")

ans = arr.flatten() # default order="C"
print(f"Flatten row wise: {ans}")

ans = arr.flatten(order = "F")
print(f"Flatten col wise: {ans}")

Original: 
[[  2  43   5]
 [  4   2   2]
 [ 54   4  56]
 [ 57 676 745]
 [  4  53  32]]
Flatten row wise: [  2  43   5   4   2   2  54   4  56  57 676 745   4  53  32]
Flatten col wise: [  2   4  54  57   4  43   2   4 676  53   5   2  56 745  32]


# Ravel()

In [76]:
data = [[2, 43, 5], [4, 2, 2], [54, 4, 56], [57, 676, 745], [4, 53, 32]]

arr = np.array(data)
print(f"Original: \n{arr}")

ans = np.reval(arr) # default order="C"
print(f"Flatten row wise: {ans}")

ans = np.reval(arr, order = "F")
print(f"Flatten col wise: {ans}")

Original: 
[[  2  43   5]
 [  4   2   2]
 [ 54   4  56]
 [ 57 676 745]
 [  4  53  32]]


AttributeError: module 'numpy' has no attribute 'reval'